### ISSUE TITLE
fail to remove zero-length branches,

### ISSUE THREAD

**Issue by limin321** [TGuillerme/dispRity#103]
Hi, 
I created a phylogeny tree, and downstream analysis requires the tree to remove all zero-length branches. so I ran remove.zero.brlen(), seems it is not working. Here is my code and outputs
```R
t <- read.tree("311coreGen.tre")
t
is.binary.tree(t)

tre <- remove.zero.brlen(t, 100,verbose = FALSE) # package dispRity
is.binary.tree(tre)
tre
```
Phylogenetic tree with 311 tips and 309 internal nodes.

Tip labels:
	Sta003, Tul001, SJ002, Sta002, LMG215, Tul004, ...
Node labels:
	, 0.000, 0.000, 0.000, 0.000, 1.000, ...

Unrooted; includes branch lengths.
[1] TRUE
longer object length is not a multiple of shorter object lengththe condition has length > 1 and only the first element will be used[1] TRUE

Phylogenetic tree with 311 tips and 309 internal nodes.

Tip labels:
	S003, T001, S002, S002, L215, T004, ...
Node labels:
	, 0.000, 0.000, 0.000, 0.000, 1.000, ...

Unrooted; includes branch lengths.

Can anyone please explain to me what is wrong with my codes? or How should I remove zero-length branches?

Best,

**Comment by TGuillerme** [comment]
Hi @limin321,

Thanks for flagging this issue and sorry for the radio silence, I was away on leave. I will have a look at it during this week and will let you know when it's solved.

Cheers,
Thomas
