### ISSUE TITLE
The use of the term series...

### ISSUE THREAD

**Issue by nhcooper123** [TGuillerme/dispRity#27]
I wonder if changing the word "series" to "subsample" might be sensible? Series really only makes sense for time slice analyses. If you truly want this to be a multidisciplinary package, then maybe subsample is more accurate. And actually, even within morpho stuff, you might want to split into two groups and compare them, so series is a really odd word choice. It might be worth thinking about other function names etc you might want to change so you can go through and replace everything at once!

**Comment by TGuillerme** [comment]
Great idea! I will fix that in the next patch! (I leave the issue open until then).

**Comment by TGuillerme** [comment]
Done.
