### ISSUE TITLE
Converting shape data arrays

### ISSUE THREAD

**Issue by EmSherratt** [TGuillerme/dispRity#35]
A # 3D array of Procrustes coordinates
pxk <- dim(A)[1] * dim(A)[2]
n <- dim(A)[3]
tmp <- aperm(A, c(3, 2, 1))
dim(tmp) <- c(n, pxk)
rownames(tmp) <- dimnames(A)[[3]] # tmp is a 2D matrix
X <- prcomp(tmp)$x # ordination matrix

**Comment by TGuillerme** [comment]
Also add geomorph.data.frame format to be passed to the function:

```
data(plethodon) 
Y.gpa <- gpagen(plethodon$land,PrinAxes=FALSE)
gdf <- geomorph.data.frame(Y.gpa)

gdf$coords

gdf <- geomorph.data.frame(Y.gpa, species = plethodon$species, site = plethodon$site)
attributes(gdf)

```

Transform geomorph into dispRity custom.subsamples object.
